CREATE TABLE CLIENTE( 
CLIENTE_ID INT NOT NULL, 
NOME VARCHAR(50) NOT NULL, 
DT_NASCIMENTO DATE NOT NULL, 
INSTAGRAM VARCHAR(50), 
PROFISSAO VARCHAR(50) 
);

CREATE TABLE EMAIL( 
EMAIL_ID INT NOT NULL, 
CLIENTE_ID INT NOT NULL, 
EMAIL VARCHAR(50) 
);

CREATE TABLE WHATSAPP( 
WHATSAPP_ID INT NOT NULL, 
CLIENTE_ID INT NOT NULL, 
WHATSAPP VARCHAR(50) 
);

CREATE TABLE AGENDAMENTO( 
AGENDAMENTO_ID INT NOT NULL, 
CLIENTE_ID INT NOT NULL, 
FUNCIONARIO_ID INT NOT NULL, 
DT_MARCADA DATE NOT NULL 
);

CREATE TABLE FUNCIONARIO( 
FUNCIONARIO_ID INT NOT NULL, 
NOME VARCHAR(50) NOT NULL, 
DT_NASCIMENTO DATE NOT NULL, 
CPF VARCHAR(50) NOT NULL 
);

CREATE TABLE CARGO( 
CARGO_ID INT NOT NULL, 
FUNCIONARIO_ID INT NOT NULL, 
CARGO VARCHAR(50) NOT NULL 
);

CREATE TABLE ATENDIMENTO( 
ATENDIMENTO_ID INT NOT NULL, 
AGENDAMENTO_ID INT NOT NULL, 
FEEDBACK INT, 
STATUS INT NOT NULL, 
DT_HORA_CHEGADA DATE NOT NULL, 
DURACAO INT NOT NULL, 
VALOR_FINAL NUMERIC(9,2) NOT NULL 
);

CREATE TABLE HISTORICO_CLIENTE( 
HISTORICO_ID INT NOT NULL, 
ATENDIMENTO_ID INT NOT NULL, 
OBJETIVO_FINAL VARCHAR(250) 
);

CREATE TABLE PROFISSIONAL( 
PROFISSIONAL_ID INT NOT NULL, 
NOME VARCHAR(50) NOT NULL, 
DT_NASCIMENTO DATE NOT NULL, 
CPF VARCHAR(50) NOT NULL 
);

CREATE TABLE ESPECIALIDADE( 
ESPECIALIDADE_ID INT NOT NULL, 
PROFISSIONAL_ID INT NOT NULL, 
ESPECIALIDADE VARCHAR(50) 
);

CREATE TABLE SERVICO( 
SERVICO_ID INT NOT NULL, 
ATENDIMENTO_ID INT NOT NULL, 
PROFISSIONAL_ID INT NOT NULL, 
PROCEDIMENTO_ID INT NOT NULL, 
VALOR_SERVICO NUMERIC(9,2) NOT NULL 
);

CREATE TABLE PROCEDIMENTO( 
PROCEDIMENTO_ID INT NOT NULL, 
TIPO_PROCEDIMENTO VARCHAR(50) NOT NULL, 
DETALHE_PROCEDIMENTO VARCHAR(250) NOT NULL, 
CUSTO_PROCEDIMENTO NUMERIC(9,2) NOT NULL 
);

CREATE TABLE PRODUTO_ESTOQUE( 
PRODUTO_ID INT NOT NULL, 
FORNECEDOR_ID INT NOT NULL, 
NOME_PRDT VARCHAR(50) NOT NULL, 
TIPO_PRDT VARCHAR(50) NOT NULL, 
QTD_PRDT INT NOT NULL, 
VALOR_UND NUMERIC(9,2) NOT NULL 
);

CREATE TABLE FORNECEDOR( 
FORNECEDOR_ID INT NOT NULL, 
NOME VARCHAR(50) NOT NULL, 
TELEFONE VARCHAR(50) NOT NULL, 
CNPJ VARCHAR(50) NOT NULL 
);

CREATE TABLE VENDA( 
VENDA_ID INT NOT NULL, 
PRODUTO_ID INT NOT NULL, 
PROFISSIONAL_ID INT NOT NULL, 
CLIENTE_ID INT NOT NULL, 
QTD_PRDT_VENDIDO INT NOT NULL, 
VLR_TOT_VENDA NUMERIC(9,2) NOT NULL 
);

CREATE TABLE HOMECARE( 
HOMECARE_ID INT NOT NULL, 
HISTORICO_ID INT NOT NULL 
);

CREATE TABLE PRODUTO_RECEITA( 
PRDT_RECEITA_ID INT NOT NULL, 
HOMECARE_ID INT NOT NULL, 
NOME_PRDT VARCHAR(50), 
FREQ_PRDT VARCHAR(250) 
);

CREATE TABLE DIAGNOSTICO_CAPILAR( 
DIAGNOSTICO_ID INT NOT NULL, 
HISTORICO_ID INT NOT NULL, 
DIAG_CAPILAR VARCHAR(250) 
);

CREATE TABLE PROCEDIMENTO_PRDT( 
PROCED_PRDT_ID INT NOT NULL, 
PRODUTO_ID INT NOT NULL, 
PROCEDIMENTO_ID INT NOT NULL 
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CLIENTE_ID);

ALTER TABLE EMAIL ADD CONSTRAINT PK_EMAIL PRIMARY KEY (EMAIL_ID);

ALTER TABLE WHATSAPP ADD CONSTRAINT PK_WHATSAPP PRIMARY KEY (WHATSAPP_ID);

ALTER TABLE AGENDAMENTO ADD CONSTRAINT PK_AGENDAMENTO PRIMARY KEY (AGENDAMENTO_ID);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (FUNCIONARIO_ID);

ALTER TABLE CARGO ADD CONSTRAINT PK_CARGO PRIMARY KEY (CARGO_ID);

ALTER TABLE ATENDIMENTO ADD CONSTRAINT PK_ATENDIMENTO PRIMARY KEY (ATENDIMENTO_ID);

ALTER TABLE HISTORICO_CLIENTE ADD CONSTRAINT PK_HISTORICO PRIMARY KEY (HISTORICO_ID);

ALTER TABLE PROFISSIONAL ADD CONSTRAINT PK_PROFISSIONAL PRIMARY KEY (PROFISSIONAL_ID);

ALTER TABLE ESPECIALIDADE ADD CONSTRAINT PK_ESPECIALIDADE PRIMARY KEY (ESPECIALIDADE_ID);

ALTER TABLE SERVICO ADD CONSTRAINT PK_SERVICO PRIMARY KEY (SERVICO_ID);

ALTER TABLE PROCEDIMENTO ADD CONSTRAINT PK_PROCEDIMENTO PRIMARY KEY (PROCEDIMENTO_ID);

ALTER TABLE PRODUTO_ESTOQUE ADD CONSTRAINT PK_PRDT_ESTOQUE PRIMARY KEY (PRODUTO_ID);

ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (FORNECEDOR_ID);

ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA PRIMARY KEY (VENDA_ID);

ALTER TABLE HOMECARE ADD CONSTRAINT PK_HOMECARE PRIMARY KEY (HOMECARE_ID);

ALTER TABLE PRODUTO_RECEITA ADD CONSTRAINT PK_PRDT_RECEITA PRIMARY KEY (PRDT_RECEITA_ID);

ALTER TABLE DIAGNOSTICO_CAPILAR ADD CONSTRAINT PK_DIAG_CAPILAR PRIMARY KEY (DIAGNOSTICO_ID);

ALTER TABLE PROCEDIMENTO_PRDT ADD CONSTRAINT PK_PROCED_PRDT PRIMARY KEY (PROCED_PRDT_ID);

ALTER TABLE EMAIL ADD CONSTRAINT FK_EMAIL_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE WHATSAPP ADD CONSTRAINT FK_WHATSAPP_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE AGENDAMENTO ADD CONSTRAINT FK_AGENDAMENTO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE AGENDAMENTO ADD CONSTRAINT FK_AGENDAMENTO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (FUNCIONARIO_ID);

ALTER TABLE CARGO ADD CONSTRAINT FK_CARGO_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (FUNCIONARIO_ID);

ALTER TABLE ATENDIMENTO ADD CONSTRAINT FK_ATENDIMENTO_AGENDAMENTO FOREIGN KEY (AGENDAMENTO_ID) REFERENCES AGENDAMENTO (AGENDAMENTO_ID);

ALTER TABLE HISTORICO_CLIENTE ADD CONSTRAINT FK_HISTORICO_CLIENTE_ATENDIMENTO FOREIGN KEY (ATENDIMENTO_ID) REFERENCES ATENDIMENTO (ATENDIMENTO_ID);

ALTER TABLE ESPECIALIDADE ADD CONSTRAINT FK_ESPECIALIDADE_PROFISSIONAL FOREIGN KEY (PROFISSIONAL_ID) REFERENCES PROFISSIONAL (PROFISSIONAL_ID);

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_ATENDIMENTO FOREIGN KEY (ATENDIMENTO_ID) REFERENCES ATENDIMENTO (ATENDIMENTO_ID);

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_PROFISSIONAL FOREIGN KEY (PROFISSIONAL_ID) REFERENCES PROFISSIONAL (PROFISSIONAL_ID);

ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_PROCEDIMENTO FOREIGN KEY (PROCEDIMENTO_ID) REFERENCES PROCEDIMENTO (PROCEDIMENTO_ID);

ALTER TABLE PRODUTO_ESTOQUE ADD CONSTRAINT FK_PRODUTO_ESTOQUE_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (FORNECEDOR_ID);

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO_ESTOQUE (PRODUTO_ID);

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_PROFISSIONAL FOREIGN KEY (PROFISSIONAL_ID) REFERENCES PROFISSIONAL (PROFISSIONAL_ID);

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE HOMECARE ADD CONSTRAINT FK_HOMECARE_HISTORICO FOREIGN KEY (HISTORICO_ID) REFERENCES HISTORICO_CLIENTE (HISTORICO_ID);

ALTER TABLE PRODUTO_RECEITA ADD CONSTRAINT FK_PRDT_RECEITA_HOMECARE FOREIGN KEY (HOMECARE_ID) REFERENCES HOMECARE (HOMECARE_ID);

ALTER TABLE DIAGNOSTICO_CAPILAR ADD CONSTRAINT FK_DIAG_CAPILAR_HISTORICO FOREIGN KEY (HISTORICO_ID) REFERENCES HISTORICO_CLIENTE (HISTORICO_ID);

ALTER TABLE PROCEDIMENTO_PRDT ADD CONSTRAINT FK_PROCEDIMENTO_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO_ESTOQUE (PRODUTO_ID);

ALTER TABLE PROCEDIMENTO_PRDT ADD CONSTRAINT FK_PRDT_PROCEDIMENTO FOREIGN KEY (PROCEDIMENTO_ID) REFERENCES PROCEDIMENTO (PROCEDIMENTO_ID);

CREATE SEQUENCE SQ_CLIENTE;

CREATE SEQUENCE SQ_EMAIL;

CREATE SEQUENCE SQ_WHATSAPP;

CREATE SEQUENCE SQ_AGENDAMENTO;

CREATE SEQUENCE SQ_FUNCIONARIO;

CREATE SEQUENCE SQ_CARGO;

CREATE SEQUENCE SQ_ATENDIMENTO;

CREATE SEQUENCE SQ_HISTORICO;

CREATE SEQUENCE SQ_PROFISSIONAL;

CREATE SEQUENCE SQ_ESPECIALIDADE;

CREATE SEQUENCE SQ_SERVICO;

CREATE SEQUENCE SQ_PROCEDIMENTO;

CREATE SEQUENCE SQ_PRODUTO;

CREATE SEQUENCE SQ_FORNECEDOR;

CREATE SEQUENCE SQ_VENDA;

CREATE SEQUENCE SQ_HOMECARE;

CREATE SEQUENCE SQ_RECEITA;

CREATE SEQUENCE SQ_DIAGNOSTICO;

CREATE SEQUENCE SQ_PROCED_PRDT;

-– TROCANDO O PADRÃO DE DATA 


ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';


insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Elena Ribeiro', '08/07/1988', 'ElenaInsta', 'Advogada');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Suely Gabeira Noite', '12/04/1989', 'SuNoite', 'Modelo');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Kaylane Vilar Araújo', '24/12/1970', 'Kay_Vi', 'Professora');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Adélia Lima Letras', '16/04/1965', 'Dentista');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Angélica Torres Belém', '30/04/1945', 'Aposentada');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Thayla Barbosa Barcelos', '21/07/1987', 'Tha_BarBar', 'Barista');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Rubi Cedraz Bandeira', '17/07/2000', 'Rub1', 'Estudante');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM, PROFISSAO) values (SQ_CLIENTE.nextVAL, 'Ester Anabela Sabala', '16/10/1985', 'Estr-Ela', 'Modelo');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO, INSTAGRAM) values (SQ_CLIENTE.nextVAL, 'Heloísa Carreira Salgado', '16/04/1965', 'HelÔ');

insert into CLIENTE (CLIENTE_ID, NOME, DT_NASCIMENTO) values (SQ_CLIENTE.nextVAL, 'Rania Ilha Abelho', '09/06/1980');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 1, 'Elena@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 2, 'Suely@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 3, 'Vilar@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 4, 'Lima@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 6, 'Thayla@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 7, 'Rubi@Email.com');

insert into EMAIL (EMAIL_ID, CLIENTE_ID, EMAIL) values (SQ_EMAIL.nextVAL, 8, 'Ester@Email.com');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 1, '99999-9652');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 2, '99999-9762');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 3, '99999-9852');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 4, '99999-9003');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 5, '99985-9111');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 6, '99779-3212');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 9, '91119-9652');

insert into WHATSAPP (WHATSAPP_ID, CLIENTE_ID, WHATSAPP) values (SQ_WHATSAPP.nextVAL, 10, '99995-9542');

INSERT INTO FUNCIONARIO (FUNCIONARIO_ID, NOME, DT_NASCIMENTO, CPF) VALUES (SQ_FUNCIONARIO.NEXTVAL, 'Omar Castanheira Fortunato', '01/02/1983', '000.111.222-33');

INSERT INTO FUNCIONARIO (FUNCIONARIO_ID, NOME, DT_NASCIMENTO, CPF) VALUES (SQ_FUNCIONARIO.NEXTVAL, 'Ludmila Ginjeira Eiró', '02/12/1985', '012.123.234-34');

INSERT INTO FUNCIONARIO (FUNCIONARIO_ID, NOME, DT_NASCIMENTO, CPF) VALUES (SQ_FUNCIONARIO.NEXTVAL, 'Piedade Lamenha Lancastre', '28/03/1979', '999.888.777-66');

INSERT INTO FUNCIONARIO (FUNCIONARIO_ID, NOME, DT_NASCIMENTO, CPF) VALUES (SQ_FUNCIONARIO.NEXTVAL, 'Oriana Zagalo Belchior', '15/08/1977', '000.111.222-33');

INSERT INTO FUNCIONARIO (FUNCIONARIO_ID, NOME, DT_NASCIMENTO, CPF) VALUES (SQ_FUNCIONARIO.NEXTVAL, 'Sílvia Vilarinho Frade', '31/07/1991', '000.111.222-33');

insert into PROFISSIONAL (PROFISSIONAL_ID, nome, dt_nascimento, CPF) values (SQ_PROFISSIONAL.nextVAL, 'Duarte Aldeia Gorjão', '01/01/1970', '333.444.555-66');

insert into PROFISSIONAL (PROFISSIONAL_ID, nome, dt_nascimento, CPF) values (SQ_PROFISSIONAL.nextVAL, 'Aisha Serro Taborda', '02/01/1985', '454.565.676-78');

insert into PROFISSIONAL (PROFISSIONAL_ID, nome, dt_nascimento, CPF) values (SQ_PROFISSIONAL.nextVAL, 'Taísa Regueira Canário', '22/11/1988', '357.753.456-71');

insert into PROFISSIONAL (PROFISSIONAL_ID, nome, dt_nascimento, CPF) values (SQ_PROFISSIONAL.nextVAL, 'Vilma Espargosa Balsemão', '11/05/1991', '123.321.147-54');

insert into PROFISSIONAL (PROFISSIONAL_ID, nome, dt_nascimento, CPF) values (SQ_PROFISSIONAL.nextVAL, 'Indira Noite Milheiriço', '15/06/1975', '666.666.666-66');

INSERT INTO FORNECEDOR (FORNECEDOR_ID, NOME, TELEFONE, CNPJ) VALUES (SQ_FORNECEDOR.NEXTVAL, 'Khadija Meneses Frazão', '99887-1234', '11.222.333/0001-11');

INSERT INTO FORNECEDOR (FORNECEDOR_ID, NOME, TELEFONE, CNPJ) VALUES (SQ_FORNECEDOR.NEXTVAL, 'Gil Quina Lages', '99778-9874', '13.465.798/0001-65');

INSERT INTO FORNECEDOR (FORNECEDOR_ID, NOME, TELEFONE, CNPJ) VALUES (SQ_FORNECEDOR.NEXTVAL, 'Sandro Rosário Vilanova', '96687-1234', '85.425.123/0001-71');

INSERT INTO FORNECEDOR (FORNECEDOR_ID, NOME, TELEFONE, CNPJ) VALUES (SQ_FORNECEDOR.NEXTVAL, 'Vasco Ferrão Neiva', '95123-3215', '15.851.751/0001-18');

INSERT INTO FORNECEDOR (FORNECEDOR_ID, NOME, TELEFONE, CNPJ) VALUES (SQ_FORNECEDOR.NEXTVAL, 'Muhammad Moreno Franca', '95557-1234', '77.666.777/0001-51');

INSERT INTO CARGO(CARGO_ID, FUNCIONARIO_ID, CARGO) VALUES (SQ_CARGO.NEXTVAL, '1', 'Recepcionista');

INSERT INTO CARGO(CARGO_ID, FUNCIONARIO_ID, CARGO) VALUES (SQ_CARGO.NEXTVAL, '2', 'auxiliar de limpeza');

INSERT INTO CARGO(CARGO_ID, FUNCIONARIO_ID, CARGO) VALUES (SQ_CARGO.NEXTVAL, '3', 'auxiliar de limpeza');

INSERT INTO CARGO(CARGO_ID, FUNCIONARIO_ID, CARGO) VALUES (SQ_CARGO.NEXTVAL, '4', 'recepcionista');

INSERT INTO CARGO(CARGO_ID, FUNCIONARIO_ID, CARGO) VALUES (SQ_CARGO.NEXTVAL, '5', 'Auxiliar');

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 1, 'Maquiagem' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 2, 'Maquiagem' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 3, 'Maquiagem' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 4, 'Maquiagem' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 5, 'Manicure' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 5, 'Pedicure' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 1, 'Cabelo' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 2, 'Cabelo' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 3, 'Cabelo' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 4, 'Cabelo' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 1, 'Química' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 2, 'Química' );

insert into ESPECIALIDADE (ESPECIALIDADE_ID, PROFISSIONAL_ID, ESPECIALIDADE) VALUES (SQ_ESPECIALIDADE.NEXTVAL, 3, 'Química' );



INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Shampoo Miracle 300ml', 'Shampoo', 30, 60 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Truss Condicionador Basic 2,400ml', 'Condicionador', 15, 200 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Condicionador Ultra Hydration 300ml', 'Condicionador', 30, 60 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Tinta Permanente Truss Color 60g - 7.1 Louro Cinza', 'Tinta de Cabelo', 21, 30 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Tinta Permanente Truss Color 60g - 8.0 Louro Claro', 'Tinta de Cabelo', 22, 30 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Tinta Permanente Truss Color 60g - 1.0 Preto', 'Tinta de Cabelo', 11, 30 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Net Mask 550g', 'Papel Laminado', 50, 100 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 1, 'Papel Laminado para Mechas', 'Papel Laminado', 50, 100 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 2, 'Kérastase Nutritive Bain Satin 1 200ml', 'Shampoo', 30, 120 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 2, 'Kérastase Genesis Fondant Renforcateur 200ml', 'Condicionador', 30, 120 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 2, 'LOréal Professionnel Diarichesse 1.0 Preto', 'Tinta de Cabelo', 15, 30 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 2, 'LOréal Professionnel Diarichesse 8.0 Louro Claro', 'Tinta de Cabelo', 16, 30 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 2, 'LOréal Professionnel Diarichesse 7.0 Louro Médio', 'Tinta de Cabelo', 10, 30 );



INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Love', 'Esmalte', 11, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Malícia', 'Esmalte', 12, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Nude', 'Esmalte', 13, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Preto Sépia', 'Esmalte', 18, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Rainha da Pista Toda', 'Esmalte', 12, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Renda', 'Esmalte', 10, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Terracota que provoca', 'Esmalte', 9, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Toque de ira', 'Esmalte', 2, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Base fortalecedora', 'Esmalte', 5, 5 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 3, 'Esmaltes Risque - Escarlate', 'Esmalte', 13, 5 );


INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 4, 'Tesoura Reta Aço Inox Mundial S/A ', 'Tesoura de unha', 10, 10 );

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 4, 'Alicate Cutícula Classic, Mundial S/A, Prateado ', 'Alicate de cutícula', 10, 10 );


INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 4, 'Tesoura Cabelo Laser 5" Flex, Mundial, Preto', 'Tesoura de Cabelo', 10, 50 );


INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 5, 'Secador Taiff Tourmaline, 2100W, 220V', 'Secador de Cabelo', 10, 250);

INSERT INTO PRODUTO_ESTOQUE (PRODUTO_ID, FORNECEDOR_ID, NOME_PRDT, TIPO_PRDT, QTD_PRDT, VALOR_UND) VALUES (SQ_PRODUTO.NEXTVAL, 5, 'Aparador de Pelos Mondial Super Groom 6 Bivolt', 'Maquina de Cabelo', 10, 100);

SELECT * FROM FUNCIONARIO JOIN CARGO USING (FUNCIONARIO_ID);

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 1, 1, '05/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 2, 1, '15/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 3, 1, '21/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 5, 1, '11/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 4, 1, '13/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 8, 1, '24/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 10, 1, '05/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 9, 1, '10/01/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 1, 1, '05/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 2, 1, '15/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 4, 1, '13/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 6, 1, '17/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 7, 1, '13/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 3, 1, '21/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 10, 1, '05/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 1, 1, '05/03/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 3, 1, '21/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 4, 1, '15/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 6, 1, '19/02/2022');

INSERT INTO AGENDAMENTO (AGENDAMENTO_ID, CLIENTE_ID, FUNCIONARIO_ID, DT_MARCADA) VALUES (SQ_AGENDAMENTO.NEXTVAL, 7, 1, '15/02/2022');

SELECT * FROM AGENDAMENTO;

SELECT * FROM AGENDAMENTO;

SELECT * FROM AGENDAMENTO;

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 1, 10, 1, '05/01/2022 15:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 2, 9, 1, '15/01/2022 09:30:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 3, 8, 1, '21/01/2022 16:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 5, 7, 1, '13/01/2022 12:30:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 18, 10, 1, '15/02/2022 14:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 20, 9, 1, '15/02/2022 10:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 7, 8, 1, '05/01/2022 11:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 9, 7, 1, '05/02/2022 13:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 19, 6, 1, '19/02/2022 15:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 14, 10, 1, '21/02/2022 12:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 15, 10, 1, '05/02/2022 16:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 16, 10, 1, '05/03/2022 15:00:00', 60, 99);

INSERT INTO ATENDIMENTO(ATENDIMENTO_ID, AGENDAMENTO_ID, FEEDBACK, STATUS, DT_HORA_CHEGADA,  DURACAO, VALOR_FINAL ) VALUES (SQ_ATENDIMENTO.NEXTVAL, 17, 9, 1, '21/02/2022 13:00:00', 60, 99);

SELECT * FROM ATENDIMENTO;

SELECT * FROM AGENDAMENTO;

SELECT * FROM ATENDIMENTO;

SELECT * FROM ATENDIMENTO ORDER BY AGENDAMENTO_ID;

SELECT * FROM ATENDIMENTO ORDER BY AGENDAMENTO_ID;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/01/2022 15:00:00' WHERE AGENDAMENTO_ID = 1;

SELECT * FROM ATENDIMENTO ORDER BY AGENDAMENTO_ID;

SELECT * FROM AGENDAMENTO;

SELECT * FROM ATENDIMENTO ORDER BY AGENDAMENTO_ID;

SELECT * FROM AGENDAMENTO;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/01/2022 15:00:00' WHERE AGENDAMENTO_ID = 1;

UPDATE AGENDAMENTO SET DT_MARCADA = '15/01/2022 09:00:00' WHERE AGENDAMENTO_ID = 2;

UPDATE AGENDAMENTO SET DT_MARCADA = '21/01/2022 16:00:00' WHERE AGENDAMENTO_ID = 3;

UPDATE AGENDAMENTO SET DT_MARCADA = '11/01/2022 15:00:00' WHERE AGENDAMENTO_ID = 4;

UPDATE AGENDAMENTO SET DT_MARCADA = '13/01/2022 12:00:00' WHERE AGENDAMENTO_ID = 5;

UPDATE AGENDAMENTO SET DT_MARCADA = '24/01/2022 15:00:00' WHERE AGENDAMENTO_ID = 6;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/01/2022 11:00:00' WHERE AGENDAMENTO_ID = 7;

UPDATE AGENDAMENTO SET DT_MARCADA = '10/01/2022 09:00:00' WHERE AGENDAMENTO_ID = 8;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/02/2022 13:00:00' WHERE AGENDAMENTO_ID = 9;

UPDATE AGENDAMENTO SET DT_MARCADA = '15/02/2022 15:00:00' WHERE AGENDAMENTO_ID = 10;

UPDATE AGENDAMENTO SET DT_MARCADA = '13/02/2022 15:00:00' WHERE AGENDAMENTO_ID = 11;

UPDATE AGENDAMENTO SET DT_MARCADA = '17/02/2022 15:00:00' WHERE AGENDAMENTO_ID = 12;

UPDATE AGENDAMENTO SET DT_MARCADA = '13/02/2022 15:00:00' WHERE AGENDAMENTO_ID = 13;

UPDATE AGENDAMENTO SET DT_MARCADA = '21/02/2022 12:00:00' WHERE AGENDAMENTO_ID = 14;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/02/2022 16:00:00' WHERE AGENDAMENTO_ID = 15;

UPDATE AGENDAMENTO SET DT_MARCADA = '05/03/2022 15:00:00' WHERE AGENDAMENTO_ID = 16;

UPDATE AGENDAMENTO SET DT_MARCADA = '21/02/2022 12:00:00' WHERE AGENDAMENTO_ID = 17;

UPDATE AGENDAMENTO SET DT_MARCADA = '15/02/2022 15:00:00' WHERE AGENDAMENTO_ID = 18;

UPDATE AGENDAMENTO SET DT_MARCADA = '19/02/2022 16:00:00' WHERE AGENDAMENTO_ID = 19;

UPDATE AGENDAMENTO SET DT_MARCADA = '15/02/2022 10:00:00' WHERE AGENDAMENTO_ID = 20;

SELECT * FROM AGENDAMENTO;

select * from produto_estoque;

select * from produto_estoque;

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 10 Vol', 'Oxidante', 13, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 20 Vol', 'Oxidante', 15, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 30 Vol', 'Oxidante', 11, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 40 Vol', 'Oxidante', 17, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 10 Vol.', 'Oxidante', 17, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 20 Vol.', 'Oxidante', 15, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 30 Vol.', 'Oxidante', 19, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 40 Vol.', 'Oxidante', 13, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'L’Oréal Paris Blond Studio Mt8 Bonder Inside', 'Pó Descolorante', 16, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor) values (sq_produto.nextval, 2, 'Truss Blanc Blond Pó Descolorante Rápido', 'Pó Descolorante', 11, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 10 Vol', 'Oxidante', 13, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 20 Vol', 'Oxidante', 15, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 30 Vol', 'Oxidante', 11, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Creme Oxidante L’Oréal Professionnel 40 Vol', 'Oxidante', 17, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 10 Vol.', 'Oxidante', 17, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 20 Vol.', 'Oxidante', 15, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 30 Vol.', 'Oxidante', 19, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Truss Color Água Oxigenada Estabilizada 40 Vol.', 'Oxidante', 13, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'L’Oréal Paris Blond Studio Mt8 Bonder Inside', 'Pó Descolorante', 16, 70);

insert into produto_estoque (produto_id, fornecedor_id, nome_prdt, tipo_prdt, qtd_prdt, valor_und) values (sq_produto.nextval, 2, 'Truss Blanc Blond Pó Descolorante Rápido', 'Pó Descolorante', 11, 70);

select * from produto_estoque;

update produto_estoque set fornecedor_id = 1 where nome_prdt like '%Truss%' 
;

select * from produto_estoque;

select * from produto_estoque;

select * from procedimento;

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Corte Feminino', 'Corte de Cabelo', 200);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Corte Masculino', 'Corte de Cabelo', 100);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Coloração', 'Tingimento Capilar', 250);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Luzes', 'Tingimento Capilar', 500);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Hidratação', 'Tratamento Capilar', 250);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Penteado', 'Penteado', 200);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Maquiagem', 'Maquiagem', 200);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Cauterização', 'Descoloração Capilar', 600);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Escova', 'Finalização', 80);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Higienização', 'Lavagem Capilar', 30);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Manicure', 'Mãos e Unhas', 25);

insert into procedimento(procedimento_id, tipo_procedimento, detalhe_procedimento, custo_procedimento) values (sq_procedimento.nextval, 'Pedicure', 'Pés e Unhas', 25);

select * from procedimento;

select * from produto_estoque;

select * from procedimento;

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 4, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 5, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 6, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 11, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 12, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 13, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 29, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 30, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 31, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 32, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 33, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 34, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 35, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 36, 3);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 29, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 30, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 31, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 32, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 33, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 34, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 35, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 36, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 37, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 38, 4);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 7, 5);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 10, 10);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 9, 10);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 3, 10);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 1, 10);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 2, 10);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 14, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 15, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 16, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 17, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 18, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 19, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 20, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 21, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 22, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 23, 11);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 14, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 15, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 16, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 17, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 18, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 19, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 20, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 21, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 22, 12);

insert into PROCEDIMENTO_PRDT (PROCED_PRDT_ID, PRODUTO_ID, PROCEDIMENTO_ID) values (SQ_PROCED_PRDT.nextval, 23, 12);

select * from PROCEDIMENTO_PRDT;

select * from profisional;

select * from atendimento;

select * from procedimento;

select * from PROFISSIONAL;

select * from atendimento;

select * from procedimento;

select * from PROFISSIONAL join especialidade using (prossional_id);

select * from atendimento;

select * from procedimento;

select * from PROFISSIONAL join especialidade using (PROFISSIONAL_ID);

select * from atendimento;

select * from procedimento;

insert into servico (servico_id, atendimento_id, prossional_id, procedimento_id, valor_servico) values (sq_servico.nextval, 1, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 1, 5, 11, 30);

select * from PROFISSIONAL join especialidade using (PROFISSIONAL_ID);

select * from atendimento;

select * from procedimento;

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 1, 4, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 1, 1, 8, 700);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 1, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 2, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 2, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 2, 3, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 3, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 3, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 3, 2, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 3, 4, 4, 500);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 4, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 4, 2, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 4, 1, 4, 500);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 5, 4, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 5, 2, 8, 700);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 5, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 6, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 6, 2, 8, 700);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 6, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 6, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 7, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 7, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 7, 1, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 7, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 8, 1, 4, 500);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 8, 4, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 8, 2, 10, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 8, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 8, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 9, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 9, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 9, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 9, 3, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 9, 4, 10, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 10, 2, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 10, 4, 4, 500);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 10, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 11, 3, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 11, 4, 10, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 11, 2, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 11, 4, 4, 500);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 12, 4, 1, 200);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 12, 1, 8, 700);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 12, 4, 9, 80);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 13, 5, 12, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 13, 5, 11, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 13, 4, 10, 30);

insert into servico (servico_id, atendimento_id, PROFISSIONAL_ID, procedimento_id, valor_servico) values (sq_servico.nextval, 13, 4, 9, 80);

select * from atendimento;

select * from servico order by valor_servico;

select * from atendimento;

select * from servico order by id_atendimento;

select * from atendimento;

select * from servico order by ATENDIMENTO_ID;

update atendimento set valor_final = 1100 where ATENDIMENTO_ID = 1;

update atendimento set valor_final = 1100 where ATENDIMENTO_ID = 1;

update atendimento set valor_final = 260 where ATENDIMENTO_ID = 2;

update atendimento set valor_final = 840 where ATENDIMENTO_ID = 3;

update atendimento set valor_final = 610 where ATENDIMENTO_ID = 4;

update atendimento set valor_final = 980 where ATENDIMENTO_ID = 5;

update atendimento set valor_final = 840 where ATENDIMENTO_ID = 6;

update atendimento set valor_final = 340 where ATENDIMENTO_ID = 7;

update atendimento set valor_final = 840 where ATENDIMENTO_ID = 8;

update atendimento set valor_final = 370 where ATENDIMENTO_ID = 9;

update atendimento set valor_final = 610 where ATENDIMENTO_ID = 10;

update atendimento set valor_final = 710 where ATENDIMENTO_ID = 11;

update atendimento set valor_final = 980 where ATENDIMENTO_ID = 12;

update atendimento set valor_final = 170 where ATENDIMENTO_ID = 13;

select * from atendimento;

select * from produto_estoque;

select * from profissional;

select * from cliente;

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 1, 2, 2, 130);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 1, 2, 2, 1, 130);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 14, 5, 3, 1, 7);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 15, 5, 6, 1, 7);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 16, 5, 10, 1, 7);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 17, 5, 9, 1, 7);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 2, 1, 8, 1, 300);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 10, 3, 6, 1, 140);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 9, 3, 6, 1, 140);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 24, 5, 3, 1, 12);

Insert into venda (venda_id, produto_id, profissional_id, cliente_id, qtd_prdt_vendido, vlr_tot_venda) values (sq_venda.nextval, 24, 5, 3, 1, 12);


